name: Clone
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run action
        uses: andrewthetechie/gha-clone-releases@v1.7.0
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          src_repo: ProjectVillage/PVNH-Launcher
          dst_repo: ProjectVillage/PVNH-GO
          copy_assets: true
